variable "aws_region" {
  description = "AWS region to deploy to"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Name prefix for all resources"
  type        = string
  default     = "jenkins-k8s"
}

variable "instance_type" {
  description = "EC2 instance type for Jenkins and K8s nodes (kubeadm needs >= 2 vCPU on master)"
  type        = string
  default     = "t3.medium"
}

variable "key_name" {
  description = "Name to assign to the AWS key pair created from public_key_path"
  type        = string
  default     = "project"
}

variable "public_key_path" {
  description = "Path on the deploy EC2 to the SSH public key generated by setup-deploy-server.sh (e.g. ~/.ssh/project.pub)"
  type        = string
}

variable "ssh_ingress_cidr" {
  description = "CIDR block allowed to SSH into the EC2 instances. Set to your public IP/32 for security."
  type        = string
  default     = "0.0.0.0/0"
}

variable "jenkins_ingress_cidr" {
  description = "CIDR block allowed to reach Jenkins on port 8080. Set to your public IP/32 for security."
  type        = string
  default     = "0.0.0.0/0"
}

variable "nodeport_ingress_cidr" {
  description = "CIDR block allowed to reach the K8s NodePort range (30000-32767)."
  type        = string
  default     = "0.0.0.0/0"
}

variable "root_volume_size_gb" {
  description = "Root EBS volume size in GiB for each EC2 instance"
  type        = number
  default     = 20
}
