#!/bin/bash
# Run on the K8s worker EC2 to join the cluster.
#
# This script is a placeholder — the real `kubeadm join ...` command is
# generated by `setup-k8s-master.sh` on the master and contains a unique
# token + CA cert hash. Copy that command and run it on the worker:
#
#   sudo kubeadm join <master-private-ip>:6443 --token <...> \
#        --discovery-token-ca-cert-hash sha256:<...>
#
# If you've lost the original join command, regenerate it on the master:
#
#   sudo kubeadm token create --print-join-command
#
# Then verify on the master:
#
#   kubectl get nodes
#
echo "This is a documentation script. See comments above for the actual join command."
exit 1
